// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqngjdnvpyaoahlrspda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbmdqZG52cHlhb2FobHJzcGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTA1NTgsImV4cCI6MjA3MTUyNjU1OH0.psX72E4gzxZAgXQgkyeznIuolbAWadVJElFrbb-lryY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});